#!/bin/bash
# Setup guide for Audio/Transcription feature

echo "=========================================="
echo "Audio & Transcription System - Setup Guide"
echo "=========================================="

echo ""
echo "✅ SYSTEM STATUS:"
echo "- Audio service: Created (chatbot-audio.service.ts)"
echo "- Transcription service: Created (transcription.service.ts)"
echo "- Configuration: Created (transcription-config.ts)"
echo "- Hooks: Created (use-transcription.ts)"
echo "- Components: Created (3 components + 2 pages)"
echo "- Routes: Added to App.tsx"
echo "- Documentation: Complete (3 files)"

echo ""
echo "✅ FILES CREATED/MODIFIED:"
echo ""
echo "Services:"
echo "  📄 src/services/chatbot-audio.service.ts"
echo "  📄 src/services/transcription.service.ts"
echo ""
echo "Configuration:"
echo "  📄 src/utils/transcription-config.ts"
echo ""
echo "Hooks:"
echo "  📄 src/hooks/use-transcription.ts"
echo ""
echo "Components:"
echo "  📄 src/components/modals/chatbot-audio-modal.tsx"
echo "  📄 src/components/shared/transcription-tester.tsx"
echo ""
echo "Pages:"
echo "  📄 src/pages/chatbot-audio-page.tsx (route: /chatbot-audio)"
echo "  📄 src/pages/transcription-test-page.tsx (route: /transcription-test)"
echo ""
echo "Configuration:"
echo "  📄 .env.example - Template for environment variables"
echo ""
echo "Documentation:"
echo "  📚 AUDIO_SETUP.md - Complete setup guide"
echo "  📚 AUDIO_TESTING_GUIDE.md - Test procedures"
echo "  📚 AUDIO_CHANGES_SUMMARY.md - Summary of changes"

echo ""
echo "=========================================="
echo "🚀 QUICK START:"
echo "=========================================="
echo ""
echo "1. Start development server:"
echo "   $ npm run dev"
echo ""
echo "2. Open in browser:"
echo "   - Text Chat: http://localhost:5173/chatbot"
echo "   - Audio Chat: http://localhost:5173/chatbot-audio"
echo "   - Test Tool: http://localhost:5173/transcription-test"
echo ""
echo "3. Authorize microphone when prompted"
echo ""
echo "4. Speak a vaccination question"
echo ""
echo "5. Listen to AI response"

echo ""
echo "=========================================="
echo "⚙️ CONFIGURATION (Optional):"
echo "=========================================="
echo ""
echo "For cloud transcription providers:"
echo ""
echo "1. Copy .env.example to .env.local"
echo "2. Add your API keys:"
echo "   - Google Cloud Speech-to-Text"
echo "   - Azure Cognitive Services"
echo "   - Deepgram"
echo ""
echo "3. See AUDIO_SETUP.md for detailed setup"

echo ""
echo "=========================================="
echo "📋 FEATURES PROVIDED:"
echo "=========================================="
echo ""
echo "✓ Voice recording (max 30 seconds)"
echo "✓ Speech recognition (Web Speech API)"
echo "✓ Transcription (4 providers options)"
echo "✓ Q&A processing (local dataset)"
echo "✓ Text-to-speech synthesis"
echo "✓ Audio playback"
echo "✓ Browser compatibility detection"
echo "✓ Error handling & logging"
echo "✓ Real-time UI feedback"
echo "✓ Message history"

echo ""
echo "=========================================="
echo "🔧 TROUBLESHOOTING:"
echo "=========================================="
echo ""
echo "Microphone not working?"
echo "  → Check browser permissions (Settings → Privacy)"
echo "  → Verify microphone hardware"
echo "  → Try another browser"
echo ""
echo "No recognition?"
echo "  → Speak clearer and louder"
echo "  → Check audio levels (volume up)"
echo "  → Use /transcription-test to debug"
echo ""
echo "TypeScript errors?"
echo "  → Check: npm run build"
echo "  → Check ESLint: npm run lint"
echo ""
echo "API errors?"
echo "  → Check console (F12 → Console)"
echo "  → Verify .env.local variables"
echo "  → Check network (F12 → Network)"

echo ""
echo "=========================================="
echo "📚 DOCUMENTATION:"
echo "=========================================="
echo ""
echo "Start with:"
echo "  1. AUDIO_SETUP.md - Architecture & configuration"
echo "  2. AUDIO_TESTING_GUIDE.md - How to test"
echo "  3. AUDIO_CHANGES_SUMMARY.md - What was built"
echo ""
echo "API Reference:"
echo "  • src/services/chatbot-audio.service.ts - Main audio functions"
echo "  • src/services/transcription.service.ts - Provider integrations"
echo "  • src/hooks/use-transcription.ts - React hook documentation"

echo ""
echo "=========================================="
echo "✅ SYSTEM READY FOR TESTING!"
echo "=========================================="
echo ""
echo "Next: npm run dev && open http://localhost:5173/chatbot-audio"
echo ""
